### ISSUE TITLE
Do not enforce 1024 pool size on require

### ISSUE THREAD

**Issue by floatdrop** [nodules/asker#106]
Require of `asker` have side-effects:

```js
var http = require('http');
console.log(http.Agent.defaultMaxSockets);
require('asker');
console.log(http.Agent.defaultMaxSockets);
```

Outputs:

```
5
1024
```

I believe [this code](https://github.com/nodules/asker/blob/master/lib/asker.js#L239-L245) is causing it.

**Comment by kaero** [comment]
Oh, it's known historical issue =(
Sorry, but i think, we would not fix it in 0.x branch to avoid unexpected behavior for current users. It will be fixed in 1.0 with node.js 0.12 and io.js support where will be a bunch of another incompatibilities.

**Comment by floatdrop** [comment]
Oh, bummer. If inside application I will tune `defaultMaxSockets` to `4096` it will be erased. :(

**Comment by kaero** [comment]
$#@, any suggestions? :)

**Comment by floatdrop** [comment]
Document it and fix in 1.0 :dog:

**Comment by 1999** [comment]
@kaero а 1.0 скоро/soon?

**Comment by Flackus** [comment]
@1999 discussion is here https://github.com/nodules/asker/pull/110

Enforcing would be removed.
