### ISSUE TITLE
Should asker stop buffering response on request abort?

### ISSUE THREAD

**Issue by doochik** [nodules/asker#122]
In some cases `data` event can be fired after request abort. Asker continues buffering response (https://github.com/nodules/asker/blob/acc28e620c5cf1ef50b31bb470f8e94984a43bea/lib/asker.js#L539) until `error` or `end` event will be fired.

Should we fix it? I can change event handler like this
```js
res.on('data', function(chunk) {
    if (httpRequest.rejected) {
        // clear buffer
        // body = [];
        return;
    }

    body.push(chunk);
    bodyLength += chunk.length;
});
```

**Comment by narqo** [comment]
Looks like this'll make #92 impossible to implement.

**Comment by kaero** [comment]
What you mean under _"request abort"_? `Request` hasn't a public method to abort a request.

**Comment by narqo** [comment]
@kaero I believe it's about this peace: https://github.com/nodules/asker/blob/acc28e620c5cf1ef50b31bb470f8e94984a43bea/lib/asker.js#L592-L604

**Comment by doochik** [comment]
yep

**Comment by kaero** [comment]
@doochik proposed changes looks acceptable for me, feel free to pr :)

**Comment by doochik** [comment]
Here it is :)
https://github.com/nodules/asker/pull/123

**Comment by kaero** [comment]
`+ asker@1.0.5`
