### ISSUE TITLE
Add timers to error data for custom usage

### ISSUE THREAD

**Issue by vitkarpov** [nodules/asker#124]
There's timings string in the data field of error. It'd be convenient to have time field also to get total time as number, to use within log.

Maybe `getCommonErrorData` should be kinda:

```js
Request.prototype.getCommonErrorData = function() {
    return {
        timers: this.getTimers(),
        timings: this.formatTimestamp(),
        url: this.getUrl(),
        requestId: this.options.requestId
    };
};
```

?

**Comment by vitkarpov** [comment]
@narqo

**Comment by narqo** [comment]
+ asker@1.1.0 — since now on errors contain `time` property with the data of timers.

**Comment by vitkarpov** [comment]
Thanks 👍
